name: Fetch latest Spanish data

# on:
#   repository_dispatch:
#   schedule:
#     - cron:  '0 4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest Spanish data
      run: |-
        mkdir -p spain
        cd spain
        #wget -q -O spain.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_fallecidos_long.csv"
        wget -q -O ccaa_covid19_datos_isciii_nueva_serie.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_datos_isciii_nueva_serie.csv"
        wget -q -O ccaa_covid19_fallecidos_por_fecha_defuncion_nueva_serie.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_fallecidos_por_fecha_defuncion_nueva_serie.csv"
        wget -q -O ccaa_covid19_fallecidos_por_fecha_defuncion_nueva_serie_long.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_fallecidos_por_fecha_defuncion_nueva_serie_long.csv"
        wget -q -O ccaa_covid19_fallecidos_por_fecha_defuncion_nueva_serie_original.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_fallecidos_por_fecha_defuncion_nueva_serie_original.csv"
        wget -q -O ccaa_covid19_test_realizados.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_test_realizados.csv"
        wget -q -O ccaa_ingresos_camas_convencionales_uci.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_ingresos_camas_convencionales_uci.csv"
        wget -q -O ccaa_pcr_realizadas_diarias.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_pcr_realizadas_diarias.csv"
        wget -q -O nacional_casos_personal_sanitario.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/nacional_casos_personal_sanitario.csv"
        wget -q -O nacional_covid19.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/nacional_covid19.csv"
        wget -q -O provincias_covid19_datos_isciii_nueva_serie.csv "https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/provincias_covid19_datos_isciii_nueva_serie.csv"
        echo "Done"
    - name: Commit and push Spanish data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest Spanish data: ${timestamp}" || exit 0
        git push
